version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - theonebatch
  kafka:
    build: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "job_item_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - theonebatch
  subscriber:
    build: theone
    depends_on:
      - kafka
    entrypoint:
       ["/home/sns/gradlew", ":sw-subscribe:bootRun", "-Dserver.port=8090"]
    networks:
      - theonebatch
networks:
    theonebatch:
